spring:
  data:
    mongodb:
      host: ${ICRITIC_MONGO_HOST:localhost}
      port: ${ICRITIC_MONGO_PORT:27017}
      database: ${ICRITIC_MONGO_DB:icritic}
      username: ${ICRITIC_MONGO_USER:root}
      password: ${ICRITIC_MONGO_PASSWORD:root}
  kafka:
    bootstrap-servers: ${ICRITIC_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  mail:
    host: ${ICRITIC_MAIL_HOST:localhost}
    port: ${ICRITIC_MAIL_PORT:587}
    username: ${ICRITIC_MAIL_USER:root}
    password: ${ICRITIC_MAIL_PASSWORD:root}
  application:
    properties:
      kafka-password-reset-request-topic: ${ICRITIC_KAFKA_PASSWORD_RESET_REQUEST_TOPIC:password-reset-request}
      kafka-group-id: ${ICRITIC_KAFKA_GROUP_IP:notifications}
server:
  port: 8082