spring:
  data:
    mongodb:
      uri: ${ICRITIC_MONGO_URL:mongodb://root:root@localhost:27017/icritic?authSource=admin}
      database: icritic
  kafka:
    bootstrap-servers: ${ICRITIC_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  mail:
    host: ${ICRITIC_MAIL_HOST:}
    port: ${ICRITIC_MAIL_PORT:}
    username: ${ICRITIC_MAIL_USER:}
    password: ${ICRITIC_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    properties:
      kafka-password-reset-request-topic: ${ICRITIC_KAFKA_PASSWORD_RESET_REQUEST_TOPIC:password-reset-request}
      kafka-password-reset-topic: ${ICRITIC_KAFKA_PASSWORD_RESET_TOPIC:password-reset}
      kafka-email-reset-request-topic: ${ICRITIC_KAFKA_EMAIL_RESET_REQUEST_TOPIC:email-reset-request}
      kafka-group-id: ${ICRITIC_KAFKA_GROUP_IP:notifications}
server:
  port: 8082