spring:
  data:
    mongodb:
        host: ${ICRITIC_MONGO_HOST:localhost}
        port: ${ICRITIC_MONGO_PORT:27017}
        database: ${ICRITIC_MONGO_DB:icritic}
        username: ${ICRITIC_MONGO_USER:root}
        password: ${ICRITIC_MONGO_PASSWORD:root}
  mail:
    host: ${ICRITIC_MAIL_HOST:localhost}
    port: ${ICRITIC_MAIL_PORT:587}
    username: ${ICRITIC_MAIL_USER:root}
    password: ${ICRITIC_MAIL_PASSWORD:root}
server:
  port: 8082